companyHR/Controllers/AddRemoveRolesController.cs
using company.BL.Model;
using company.DAL.Extend;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;


namespace companyHR.Controllers
{
    [Authorize]

    public class AddRemoveRolesController : Controller
    {

        private readonly UserManager<ApplicationUser> userManager;
        private readonly RoleManager<ApplictionRoles> roleManager;

        public AddRemoveRolesController(UserManager<ApplicationUser> userManager, RoleManager<ApplictionRoles> roleManager)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
        }


        public async Task<IActionResult> Index()
        {
            var result = roleManager.Roles;
            List<UsersRolesVm> usersRoles = new List<UsersRolesVm>();
            foreach (var role in result)
            {

                var users = await userManager.GetUsersInRoleAsync(role.Name);
                if (users.Count != 0)
                {
                    foreach (var user in users)
                    {
                        UsersRolesVm usersRolesVm = new UsersRolesVm();
                        usersRolesVm.UserId = user.Id;
                        usersRolesVm.UserNAME = user.UserName;
                        usersRolesVm.RoleID = role.Id;
                        usersRolesVm.RoleName = role.Name;
                        usersRoles.Add(usersRolesVm);
                    }

                }

            }
            return View(usersRoles);
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(UsersRolesVm usersRoles)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var user = await userManager.FindByIdAsync(usersRoles.UserId);
                    var result = await userManager.AddToRoleAsync(user, usersRoles.RoleName);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var item in result.Errors)
                        {
                            ModelState.AddModelError("", item.Description);
                        }
                        return View(usersRoles);
                    }
                }
                else
                {
                    return View(usersRoles);

                }

            }
            catch (Exception ex)
            {
                return View(usersRoles);

            }
        }


        [HttpGet]
        public async Task<IActionResult> Delete(string UserId, string RoleID)
        {
            try
            {
                var role = await roleManager.FindByIdAsync(RoleID);
                var user = await userManager.FindByIdAsync(UserId);
                UsersRolesVm usersRoles = new UsersRolesVm()

                {
                    RoleName = role.Name,
                    RoleID = role.Id,
                    UserId = user.Id,
                    UserNAME = user.UserName

                };

                if (ModelState.IsValid)
                {
                    return View(usersRoles);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }

            catch
            {
                return RedirectToAction("Index");

            }

        }



        [HttpPost]
        public async Task<IActionResult> Delete(UsersRolesVm usersRoles)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    ApplicationUser user = await userManager.FindByIdAsync(usersRoles.UserId);
                    var result = await userManager.RemoveFromRoleAsync(user, usersRoles.RoleName);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError("", error.Description);
                        }
                        return View(usersRoles);
                    }
                }
                else
                {
                    return View(usersRoles);

                }
            }
            catch
            {
                ModelState.AddModelError("", "Dont Remove");
                return View(usersRoles);
            }
        }


        [HttpGet]
        public async Task<IActionResult> Details(string UserId, string RoleID)
        {
            try
            {
                var role = await roleManager.FindByIdAsync(RoleID);
                var user = await userManager.FindByIdAsync(UserId);
                UsersRolesVm usersRoles = new UsersRolesVm()

                {
                    RoleName = role.Name,
                    RoleID = role.Id,
                    UserId = user.Id,
                    UserNAME = user.UserName

                };

                if (ModelState.IsValid)
                {
                    return View(usersRoles);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }

            catch
            {
                return RedirectToAction("Index");

            }

        }
    }
}

companyHR/Controllers/RolesController.cs
using company.BL.Model;
using company.DAL.Extend;
using company.DAL.Repository.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualBasic;
using AutoMapper;
using System.Data;

namespace companyHR.Controllers
{
    [Authorize]

    public class RolesController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly RoleManager<ApplictionRoles> roleManager;
        private readonly IMapper mapper;

        public RolesController(UserManager<ApplicationUser> userManager,RoleManager<ApplictionRoles> roleManager, IMapper mapper) 
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
            this.mapper = mapper;
        }    
        public IActionResult  Index()
        {
            IEnumerable<ApplictionRoles> result =  roleManager.Roles;
            var data = mapper.Map<IEnumerable<ApplictionRolesVm>>(result);

            return View(data);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public  async Task<IActionResult> Create(ApplictionRolesVm identityRole)
        {
            try
            {


                return await CreateRole(identityRole);
            }
            catch
            {
                return View(identityRole);

            }

        }

        private async Task<IActionResult> CreateRole(ApplictionRolesVm identityRole)
        {


            if (ModelState.IsValid)
            {
                var role = new ApplictionRoles()
                {
                    Name = identityRole.Name,
                    NormalizedName = identityRole.Name.ToLower(),
                };






                var resule = await roleManager.CreateAsync(role);
                if (resule.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var item in resule.Errors)
                    {
                        ModelState.AddModelError("", item.Description);

                    }
                    return View(identityRole);

                }
            }
            ModelState.AddModelError("", "Role Name is requird");
            return View(identityRole);
        }
        #region EditRole
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {

            ApplictionRoles role = await roleManager.FindByIdAsync(id);
            var data = mapper.Map<ApplictionRolesVm>(role);

            return View(data);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(ApplictionRolesVm identityRole)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var data = mapper.Map<ApplictionRoles> (identityRole);

                    return await EditRole(data);

                }
                else
                {
                    return View(identityRole);

                }

            }
            catch (Exception ex)
            {
                return View(identityRole);
            }
        }

        private async Task<IActionResult> EditRole(IdentityRole identityRole)
        {
            var role = await roleManager.FindByIdAsync(identityRole.Id);
            role.Name = identityRole.Name;
            role.NormalizedName = identityRole.Name.ToUpper();
            var result = await roleManager.UpdateAsync(role);
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }
                return View(identityRole);
            }
        }
        #endregion

        #region DeleteRole
        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {



            ApplictionRoles role = await roleManager.FindByIdAsync(id);
            var data = mapper.Map<ApplictionRolesVm>(role);

            return View(data);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(ApplictionRolesVm identityRole)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var data = mapper.Map<ApplictionRoles>(identityRole);

                    return await DeleteRole(data);

                }
                else
                {
                    return View(identityRole);

                }

            }
            catch (Exception ex)
            {
                return View(identityRole);
            }
        }
        private async Task<IActionResult> DeleteRole(ApplictionRoles identityRole)
        {
            ApplictionRoles role = await roleManager.FindByIdAsync(identityRole.Id);
            var result = await roleManager.DeleteAsync(role);
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            else
            {
                var data = mapper.Map<ApplictionRolesVm>(identityRole);

                return View(data);
            }
        }
        #endregion

        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            ApplictionRoles role = await roleManager.FindByIdAsync(id);
            var data = mapper.Map<ApplictionRolesVm>(role);

            return View(data);
        }


    }
}
 

companyHR/Views/AddRemoveRoles/Create.cshtml
@using company.DAL.Extend;
@inject RoleManager<ApplictionRoles> roles;
@inject UserManager<ApplicationUser> users;
@model company.BL.Model.UsersRolesVm

@{
    ViewBag.Title = "Add User role";
}
<div class="card">
    <div class="card-body">
       <div asp-validation-summary="All" class="text-danger" ></div> 
 <br />


        <form class="" id="form_validation" asp-controller="AddRemoveRoles" asp-action="create" method="post">
                              
            <div class="row g-3 mb-3">

                <div class="col-md-6">
                    <div class="form-floating ">

                        <select asp-for="UserId" class="form-select" id="UserId" aria-label="UserId">
                            <option value="">-- Please select user  --</option>
                            @{
                                foreach (var item in users.Users)
                                {
                                    <option value=@item.Id>@item.UserName</option>

                                }
                            }

                        </select>
                        <label for="UserId">User Name</label>
                    </div>
                    <span asp-validation-for="UserId" class="text-danger "></span>
                </div>
                <div class="col-md-6">
                    <div class="form-floating ">

                        <select asp-for="RoleName" class="form-select" id="vacationId" aria-label="RoleName">
                            <option value="">-- Please select role  --</option>
                            @{
                                foreach (var item in roles.Roles)
                                {
                                    <option value=@item.Name>@item.Name</option>
                                }
                            }

                        </select>
                        <label for="RoleName">Role Name</label>
                    </div>
                    <span asp-validation-for="RoleName" class="text-danger "></span>
                </div>

                </div>
                      
                    <button class="btn btn-primary waves-effect" type="submit">Create</button>
                    <button class="btn btn-primary waves-effect" type="reset">Cancel</button>
            <a asp-controller="AddRemoveRoles" asp-action="index" class="btn btn-success">Back</a>


              
              
  </form>
</div>
</div>
@section MicrosoftValidation{

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
   
    }
@section PageTitle {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="home" asp-action="index">Home</a></li>
        <li class="breadcrumb-item"> <a asp-controller="AddRemoveRoles" asp-action="index"> Users Roles </a></li>
        <li class="breadcrumb-item"> <a>Add User Role</a></li>

    </ol>
}

companyHR/Views/AddRemoveRoles/Index.cshtml
    
@model List< company.BL.Model.UsersRolesVm>
@{
    ViewBag.Title = "Users Roles";
}

<!-- Exportable Table -->
<section class="section">
    <div class="row justify-content-end ">
        <div class="col-2 text-end">
            <a class="btn btn-primary" asp-controller="AddRemoveRoles" asp-action="Create">Create</a>
        </div>

    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">

                    <!-- Table with stripped rows -->
                    <table class="table datatable  table-striped  ">

                        <thead>
                            <tr>
                                <th scope="col">Role Name</th>
                                <th scope="col">User Name</th>
                                <th scope="col">DETAILS</th>
                                <th scope="col">Delete</th>

                            </tr>
                        </thead>

                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.RoleName</td>
                                    <td>@item.UserNAME</td>

                                    <td><a asp-controller="AddRemoveRoles" asp-action="details" asp-route-RoleID="@item.RoleID" asp-route-UserId="@item.UserId" class="btn btn-info">Details</a></td>
                                    <td>
                                        <a asp-controller="AddRemoveRoles" asp-action="Delete" asp-route-RoleID="@item.RoleID" asp-route-UserId="@item.UserId"
                                           class="btn btn-danger">Delete</a>
                                    </td>

                                </tr>
                            }

                        </tbody>
                    </table>
                    <!-- End Table with stripped rows -->
                </div>
            </div>
        </div>
    </div>
</section>
<!-- #END# Exportable Table -->
<!-- Jquery DataTable Plugin Js -->
 
@section DataTabelScripts {
       


}
@section PageTitle {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="home" asp-action="index">Home</a></li>
        <li class="breadcrumb-item"> <a asp-controller="Roles" asp-action="index">Roles </a></li>
    </ol>
}

companyHR/Views/AddRemoveRoles/delete.cshtml
@using company.DAL.Extend;
@inject RoleManager<IdentityRole> roles;
@inject UserManager<ApplicationUser> users;
@model company.BL.Model.UsersRolesVm

@{
    ViewBag.Title = "Delete User role";
}
<div class="card">
    <div class="card-body">

        <br />


        <form class="" id="form_validation" asp-controller="AddRemoveRoles" asp-action="Delete" method="post">

            <div class="row g-3 mb-3">

                <div class="col-md-6">
                    <div class="form-floating ">

                        <select asp-for="UserId" class="form-select" id="UserId" aria-label="UserId">
                            <option value="">-- Please select user  --</option>
                            @{
                                foreach (var item in users.Users)
                                {
                                    <option value=@item.Id>@item.UserName</option>

                                }
                            }

                        </select>
                        <label for="UserId">User Name</label>
                    </div>
                    <span asp-validation-for="UserId" class="text-danger "></span>
                </div>
                <div class="col-md-6">
                    <div class="form-floating ">

                        <select asp-for="RoleName" class="form-select" id="vacationId" aria-label="RoleName">
                            <option value="">-- Please select role  --</option>
                            @{
                                foreach (var item in roles.Roles)
                                {
                                    <option value=@item.Name>@item.Name</option>
                                }
                            }

                        </select>
                        <label for="RoleName">Role Name</label>
                    </div>
                    <span asp-validation-for="RoleName" class="text-danger "></span>
                </div>

            </div>

            <button class="btn btn-primary waves-effect" type="submit">Delete</button>
            <a asp-controller="AddRemoveRoles" asp-action="index" class="btn btn-success">Back</a>




        </form>
    </div>
</div>
@section MicrosoftValidation{

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    }
@section PageTitle {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="home" asp-action="index">Home</a></li>
        <li class="breadcrumb-item"> <a asp-controller="AddRemoveRoles" asp-action="index"> Users Roles </a></li>
        <li class="breadcrumb-item"> <a>Delete User Role</a></li>

    </ol>
}

companyHR/Views/AddRemoveRoles/details.cshtml
@using company.DAL.Extend;
@inject RoleManager<IdentityRole> roles;
@inject UserManager<ApplicationUser> users;
@model company.BL.Model.UsersRolesVm

@{
    ViewBag.Title = " User role Details";
}
<div class="card">
    <div class="card-body">

        <br />



            <div class="row g-3 mb-3">

                <div class="col-md-6">
                    <div class="form-floating ">

                        <select asp-for="UserId" class="form-select" id="UserId" aria-label="UserId">
                            <option value="">-- Please select user  --</option>
                            @{
                                foreach (var item in users.Users)
                                {
                                    <option value=@item.Id>@item.UserName</option>

                                }
                            }

                        </select>
                        <label for="UserId">User Name</label>
                    </div>
                    <span asp-validation-for="UserId" class="text-danger "></span>
                </div>
                <div class="col-md-6">
                    <div class="form-floating ">

                        <select asp-for="RoleName" class="form-select" id="vacationId" aria-label="RoleName">
                            <option value="">-- Please select role  --</option>
                            @{
                                foreach (var item in roles.Roles)
                                {
                                    <option value=@item.Name>@item.Name</option>
                                }
                            }

                        </select>
                        <label for="RoleName">Role Name</label>
                    </div>
                    <span asp-validation-for="RoleName" class="text-danger "></span>
                </div>

            </div>

            <a asp-controller="AddRemoveRoles" asp-action="index" class="btn btn-success">Back</a>




    </div>
</div>
@section MicrosoftValidation{

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    }
@section PageTitle {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="home" asp-action="index">Home</a></li>
        <li class="breadcrumb-item"> <a asp-controller="AddRemoveRoles" asp-action="index"> Users Roles </a></li>
        <li class="breadcrumb-item"> <a> User role Details</a></li>

    </ol>
}