companyHR/Controllers/EmployeesVacationController.cs
using AutoMapper;
using company.BL.Model;
using company.DAL.Repository.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RepositoryUsingEFinMVC.GenericRepository;

namespace companyHR.Controllers
{
    [Authorize]

    public class EmployeesVacationController : Controller
    {
        private IGenericRepository<employeesVacation> employeesVacationRep;

        private readonly IMapper _mapper;
        public EmployeesVacationController(IGenericRepository<employeesVacation> _EmployeesVacation, IMapper mapper)
        {

            this.employeesVacationRep = _EmployeesVacation;
            this._mapper = mapper;
        }
        public IActionResult Index()
        {
            var data = employeesVacationRep.GetAll(p => p.vacation, p => p.employee);
            var model = _mapper.Map<IEnumerable<EmployeesVacationVM>>(data);
            return View(model);
        }
        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]

        public IActionResult Create(EmployeesVacationVM model)
        {
            try
            {
                ModelState.Remove("vacation");
                ModelState.Remove("employee");
                if (ModelState.IsValid)
                {
                    var data = _mapper.Map<employeesVacation>(model);
                    employeesVacationRep.Insert(data);

                    return RedirectToAction("Index");
                }
                else
                {
                    return View(model);
                }

            }
            catch
            {
                return View(model);

            }

        }
        [HttpGet]
        public IActionResult details(int id)
        {
            var data = employeesVacationRep.GetById(id, p => p.vacation, p => p.employee);
            var model = _mapper.Map<EmployeesVacationVM>(data);
            return View(model);
        }
        [HttpGet]
        public IActionResult edit(int id)
        {
            var data = employeesVacationRep.GetById(id);
            var model = _mapper.Map<EmployeesVacationVM>(data);

            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult edit(EmployeesVacationVM model)
        {
            try
            {
                return editEmployeesVacation(model);
            }
            catch
            {
                return View(model);
            }
        }
        [HttpGet]
        public IActionResult delete(int id)
        {
            var data = employeesVacationRep.GetById(id, p => p.vacation, p => p.employee);
            var model = _mapper.Map<EmployeesVacationVM>(data);

            return View(model);
        }
        [HttpPost]
        public IActionResult delete(EmployeesVacationVM model)
        {

            try
            {
                var data = _mapper.Map<employeesVacation>(model);
                employeesVacationRep.Delete(data);

                return RedirectToAction("Index");


            }
            catch
            {
                return View();

            }
        }




        private IActionResult editEmployeesVacation(EmployeesVacationVM model)
        {
            ModelState.Remove("vacation");
            ModelState.Remove("employee");
            if (ModelState.IsValid)
            {

                var data = _mapper.Map<employeesVacation>(model);
                employeesVacationRep.Update(data);

                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }
    }
}

companyHR/Views/EmployeesVacation/Create.cshtml
@model company.BL.Model.EmployeesVacationVM

@{    
    ViewBag.Title = "Add Employee Vacation";
    // var x = emplo.GetAll();
}
<div class="card">
    <div class="card-body">
@*         <h5 class="card-title">Floating labels Form</h5>
 *@
 <br />


        <form class="" id="form_validation" asp-controller="EmployeesVacation" asp-action="create" method="post">
                              
            <div class="row g-3 mb-3">
                <div class="col-md-6">
                    <div class="form-floating ">
                        <select asp-for="employeeId" class="form-select" id="employeeId" aria-label="employeeId">
                            <option value="">-- Please select Employee  --</option>

                        </select>
                        <label for="employeeId">Employee</label>
                    </div>
                    <span asp-validation-for="employeeId" class="text-danger "></span>

                </div>
                <div class="col-md-6">
                    <div class="form-floating ">
                        <select asp-for="vacationId" class="form-select" id="vacationId" aria-label="vacationId">
                            <option value="">-- Please select Vacation  --</option>

                        </select>
                        <label for="vacationId">Bonus</label>
                    </div>
                    <span asp-validation-for="vacationId" class="text-danger "></span>

                </div>
                <div class="col-md-6">
                    <div class="form-floating">
                        <input type="date" class="form-control" asp-for="fromDate" id="fromDate" placeholder="From Date ">
                        <label for="fromDate">From Date   </label>
                    </div>
                    <span asp-validation-for="fromDate" class="text-danger "></span>

                </div>
                <div class="col-md-6">
                    <div class="form-floating">
                        <input type="date" class="form-control" asp-for="toDate" id="fromDate" placeholder="To Date ">
                        <label for="toDate">To Date   </label>
                    </div>
                    <span asp-validation-for="toDate" class="text-danger "></span>

                </div>

                </div>
                      
                    <button class="btn btn-primary waves-effect" type="submit">Create</button>
                    <button class="btn btn-primary waves-effect" type="reset">Cancel</button>
            <a asp-controller="EmployeesVacation" asp-action="index" class="btn btn-success">Back</a>


              
              
  </form>
</div>
</div>
@section MicrosoftValidation{

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script>

        $(function () {

            $("#employeeId").empty();
            $("#employeeId").append("<option value='0'>Choose Employee</option>");
            $.ajax({
                type: "POST",
                url: "/Employees/getAllEmployee",
                data: {},
                success: function (res) {
                    console.log(res);
                    $.each(res, function (i, e) {
                        $("#employeeId").append("<option value='" + e.id + "'>" + e.employeeName + "</option>");
                    });
                }
            });


            $("#vacationId").empty();
            $("#vacationId").append("<option value='0'>Choose Vacation</option>");
            $.ajax({
                type: "POST",
                url: "/Vacation/getAllVacation",
                data: {},
                success: function (res) {
                    console.log(res);
                    $.each(res, function (i, e) {
                        $("#vacationId").append("<option value='" + e.id + "'>" + e.vacationName + "</option>");
                    });
                }
            });
        });
    </script>
    }
@section PageTitle {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="home" asp-action="index">Home</a></li>
        <li class="breadcrumb-item"> <a asp-controller="EmployeesVacation" asp-action="index">Employee Vaction </a></li>
        <li class="breadcrumb-item"> <a>Add Employee Vaction </a></li>

    </ol>
}

companyHR/Views/EmployeesVacation/Index.cshtml
        
@model IEnumerable<company.BL.Model.EmployeesVacationVM>


@{
    ViewBag.Title = "Employee Vacation";
}

<!-- Exportable Table -->
<section class="section">
    <div class="row justify-content-end ">
        <div class="col-2 text-end">
            <a class="btn btn-primary" asp-controller="EmployeesVacation" asp-action="Create">Create</a>
        </div>

    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">

                    <!-- Table with stripped rows -->
                    <table class="table datatable  table-striped  ">

                        <thead>
                            <tr>
                                <th scope="col">Id</th>
                                <th scope="col">Employee Name</th>
                                <th scope="col"> vacation Name</th>
                                <th scope="col">vacation Cost</th>
                                <th scope="col"> From Date</th>
                                <th scope="col">To Date</th>
                                <th scope="col">DETAILS</th>
                                <th scope="col">EDIT</th>
                                <th scope="col">Delete</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {



                                <tr>
                                    <td> @item.id</td>
                                    <td>@item.employee.employeeName</td>
                                    <td>@item.vacation.vacationName</td>
                                    <td>@item.vacation.vacationCost</td>
                                    <td>@item.fromDate</td>
                                    <td>@item.toDate</td>


                                    <td><a asp-controller="EmployeesVacation" asp-action="details" asp-route-id="@item.id" class="btn btn-info">Details</a></td>
                                    <td><a asp-controller="EmployeesVacation" asp-action="edit" asp-route-id="@item.id" class="btn btn-warning">Edit</a></td>
                                    <td><a asp-controller="EmployeesVacation" asp-action="Delete" asp-route-id="@item.id" class="btn btn-danger">Delete</a></td>

                                </tr>
                            }

                        </tbody>
                        <!-- End Table with stripped rows -->
                </div>
            </div>
        </div>
    </div>
</section>
<!-- #END# Exportable Table -->
<!-- Jquery DataTable Plugin Js -->
 
@section DataTabelScripts {
       


}
@section PageTitle {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="home" asp-action="index">Home</a></li>
        <li class="breadcrumb-item"> <a asp-controller="EmployeesVacation" asp-action="index">Employees Vacation </a></li>
    </ol>
}

companyHR/Views/EmployeesVacation/delete.cshtml
@model company.BL.Model.EmployeesVacationVM

@{
    ViewBag.Title = "Delete Employee Vacation";
    // var x = emplo.GetAll();
}
<div class="card">
    <div class="card-body">

        <br />


        <form class="" id="form_validation" asp-controller="EmployeesVacation" asp-action="Delete" method="post">

            <div class="row g-3 mb-3">
                <div class="col-md-6">
                    <div class="form-floating ">
                        <select asp-for="employeeId" class="form-select readOnly" id="employeeId" aria-label="employeeId">
                            <option value="">-- Please select Employee  --</option>

                        </select>
                        <label for="employeeId">Employee</label>
                    </div>
                    <span asp-validation-for="employeeId" class="text-danger "></span>

                </div>
                <div class="col-md-6">
                    <div class="form-floating ">
                        <select asp-for="vacationId" class="form-select readOnly" id="vacationId" aria-label="vacationId">
                            <option value="">-- Please select Vacation  --</option>

                        </select>
                        <label for="vacationId">Bonus</label>
                    </div>
                    <span asp-validation-for="vacationId" class="text-danger "></span>

                </div>
                <div class="col-md-6">
                    <div class="form-floating">
                        <input type="text" class="form-control readOnly" asp-for="fromDate" id="fromDate" placeholder="From Date ">
                        <label for="fromDate">From Date   </label>
                    </div>
                    <span asp-validation-for="fromDate" class="text-danger "></span>

                </div>
                <div class="col-md-6">
                    <div class="form-floating">
                        <input type="text" class="form-control readOnly" asp-for="toDate" id="fromDate" placeholder="To Date ">
                        <label for="toDate">To Date   </label>
                    </div>
                    <span asp-validation-for="toDate" class="text-danger "></span>

                </div>

            </div>

            <button class="btn btn-primary waves-effect" type="submit">Delete</button>
            <a asp-controller="EmployeesVacation" asp-action="index" class="btn btn-success">Back</a>




        </form>
    </div>
</div>
@section MicrosoftValidation{

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script>

        $(function () {

            $("#employeeId").empty();
            $("#employeeId").append("<option value='0'>Choose Employee</option>");
            $.ajax({
                type: "POST",
                url: "/Employees/getAllEmployee",
                data: {},
                success: function (res) {
                    console.log(res);
                    $.each(res, function (i, e) {
                        $("#employeeId").append("<option value='" + e.id + "'>" + e.employeeName + "</option>");
                    });
                    $("#employeeId").val(@Model.employeeId);

                }
            });




            $("#vacationId").empty();
            $("#vacationId").append("<option value='0'>Choose Vacation</option>");
            $.ajax({
                type: "POST",
                url: "/Vacation/getAllVacation",
                data: {},
                success: function (res) {
                    console.log(res);
                    $.each(res, function (i, e) {
                        $("#vacationId").append("<option value='" + e.id + "'>" + e.vacationName + "</option>");
                    });
                    $("#vacationId").val(@Model.vacationId);

                }
            });


        });

        $(document).ready(function () {
            $(document).ready(() => {
            });
        });

    </script>
    }
@section PageTitle {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="home" asp-action="index">Home</a></li>
        <li class="breadcrumb-item"> <a asp-controller="EmployeesVacation" asp-action="index">Employee Vaction </a></li>
        <li class="breadcrumb-item"> <a>Delete Employee Vaction </a></li>

    </ol>
}

companyHR/Views/EmployeesVacation/details.cshtml
@model company.BL.Model.EmployeesVacationVM

@{
    ViewBag.Title = "Employee Vacation Details";
    // var x = emplo.GetAll();
}
<div class="card">
    <div class="card-body">

        <br />



            <div class="row g-3 mb-3">
                <div class="col-md-6">
                    <div class="form-floating ">
                        <select asp-for="employeeId" class="form-select readOnly" id="employeeId" aria-label="employeeId">
                            <option value="">-- Please select Employee  --</option>

                        </select>
                        <label for="employeeId">Employee</label>
                    </div>
                    <span asp-validation-for="employeeId" class="text-danger "></span>

                </div>
                <div class="col-md-6">
                    <div class="form-floating ">
                        <select asp-for="vacationId" class="form-select readOnly" id="vacationId" aria-label="vacationId">
                            <option value="">-- Please select Vacation  --</option>

                        </select>
                        <label for="vacationId">Bonus</label>
                    </div>
                    <span asp-validation-for="vacationId" class="text-danger "></span>

                </div>
                <div class="col-md-6">
                    <div class="form-floating">
                        <input type="text" class="form-control readOnly" asp-for="fromDate" id="fromDate" placeholder="From Date ">
                        <label for="fromDate">From Date   </label>
                    </div>
                    <span asp-validation-for="fromDate" class="text-danger "></span>

                </div>
                <div class="col-md-6">
                    <div class="form-floating">
                        <input type="text" class="form-control readOnly" asp-for="toDate" id="fromDate" placeholder="To Date ">
                        <label for="toDate">To Date   </label>
                    </div>
                    <span asp-validation-for="toDate" class="text-danger "></span>

                </div>

            </div>

            <a asp-controller="EmployeesVacation" asp-action="index" class="btn btn-success">Back</a>




    </div>
</div>
@section MicrosoftValidation{

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script>

        $(function () {

            $("#employeeId").empty();
            $("#employeeId").append("<option value='0'>Choose Employee</option>");
            $.ajax({
                type: "POST",
                url: "/Employees/getAllEmployee",
                data: {},
                success: function (res) {
                    console.log(res);
                    $.each(res, function (i, e) {
                        $("#employeeId").append("<option value='" + e.id + "'>" + e.employeeName + "</option>");
                    });
                    $("#employeeId").val(@Model.employeeId);

                }
            });




            $("#vacationId").empty();
            $("#vacationId").append("<option value='0'>Choose Vacation</option>");
            $.ajax({
                type: "POST",
                url: "/Vacation/getAllVacation",
                data: {},
                success: function (res) {
                    console.log(res);
                    $.each(res, function (i, e) {
                        $("#vacationId").append("<option value='" + e.id + "'>" + e.vacationName + "</option>");
                    });
                    $("#vacationId").val(@Model.vacationId);

                }
            });


        });

        $(document).ready(function () {
            $(document).ready(() => {
            });
        });

    </script>
    }
@section PageTitle {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="home" asp-action="index">Home</a></li>
        <li class="breadcrumb-item"> <a asp-controller="EmployeesVacation" asp-action="index">Employee Vaction </a></li>
        <li class="breadcrumb-item"> <a> Employee Vaction Details</a></li>

    </ol>
}

companyHR/Views/EmployeesVacation/edit.cshtml
                        
@model company.BL.Model.EmployeesVacationVM

@{    
    ViewBag.Title = "Edit Employee Vacation";
    // var x = emplo.GetAll();
}
<div class="card">
    <div class="card-body">

 <br />


        <form class="" id="form_validation" asp-controller="EmployeesVacation" asp-action="Edit" method="post">
                              
            <div class="row g-3 mb-3">
                <div class="col-md-6">
                    <div class="form-floating ">
                        <select asp-for="employeeId" class="form-select" id="employeeId" aria-label="employeeId">
                            <option value="">-- Please select Employee  --</option>

                        </select>
                        <label for="employeeId">Employee</label>
                    </div>
                    <span asp-validation-for="employeeId" class="text-danger "></span>

                </div>
                <div class="col-md-6">
                    <div class="form-floating ">
                        <select asp-for="vacationId" class="form-select" id="vacationId" aria-label="vacationId">
                            <option value="">-- Please select Vacation  --</option>

                        </select>
                        <label for="vacationId">Bonus</label>
                    </div>
                    <span asp-validation-for="vacationId" class="text-danger "></span>

                </div>
                <div class="col-md-6">
                    <div class="form-floating">
                        <input type="text" class="form-control" asp-for="fromDate" id="fromDate" placeholder="From Date ">
                        <label for="fromDate">From Date   </label>
                    </div>
                    <span asp-validation-for="fromDate" class="text-danger "></span>

                </div>
                <div class="col-md-6">
                    <div class="form-floating">
                        <input type="text" class="form-control" asp-for="toDate" id="fromDate" placeholder="To Date ">
                        <label for="toDate">To Date   </label>
                    </div>
                    <span asp-validation-for="toDate" class="text-danger "></span>

                </div>

                </div>

            <button class="btn btn-primary waves-effect" type="submit">Edit</button>
            <a asp-controller="EmployeesVacation" asp-action="index" class="btn btn-success">Back</a>


              
              
  </form>
</div>
</div>
@section MicrosoftValidation{

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script>

        $(function () {

            $("#employeeId").empty();
            $("#employeeId").append("<option value='0'>Choose Employee</option>");
            $.ajax({
                type: "POST",
                url: "/Employees/getAllEmployee",
                data: {},
                success: function (res) {
                    console.log(res);
                    $.each(res, function (i, e) {
                        $("#employeeId").append("<option value='" + e.id + "'>" + e.employeeName + "</option>");
                    });
                    $("#employeeId").val(@Model.employeeId);

                }
            });




            $("#vacationId").empty();
            $("#vacationId").append("<option value='0'>Choose Vacation</option>");
            $.ajax({
                type: "POST",
                url: "/Vacation/getAllVacation",
                data: {},
                success: function (res) {
                    console.log(res);
                    $.each(res, function (i, e) {
                        $("#vacationId").append("<option value='" + e.id + "'>" + e.vacationName + "</option>");
                    });
                    $("#vacationId").val(@Model.vacationId);

                }
            });


        });

        $(document).ready(function () {
            $(document).ready(() => {
            });
        });

    </script>
    }
@section PageTitle {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="home" asp-action="index">Home</a></li>
        <li class="breadcrumb-item"> <a asp-controller="EmployeesVacation" asp-action="index">Employee Vaction </a></li>
        <li class="breadcrumb-item"> <a>Edit Employee Vaction </a></li>

    </ol>
}