companyHR/Controllers/BonussController.cs
using AutoMapper;
using company.BL.Model;
using company.DAL.Repository.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol.Core.Types;
using RepositoryUsingEFinMVC.GenericRepository;

namespace companyHR.Controllers
{
    [Authorize]

    public class BonussController : Controller
    {
        private readonly IMapper _mapper;
        private IGenericRepository<bonuss> bonusRep;
        public BonussController(IGenericRepository<bonuss> _repository, IMapper mapper)
        {
            this.bonusRep = _repository;
            this._mapper = mapper;
        }
        
        public IActionResult Index()
        {
            var data = bonusRep.Get();
            var model = _mapper.Map<IEnumerable<BonusVM>>(data);
            return View(model);
        }
        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public IActionResult Create(BonusVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var data = _mapper.Map<bonuss>(model);
                    bonusRep.Insert(data);
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(model);
                }
            }
            catch
            {
                return View(model);
            }
        }
        [HttpGet]
        public IActionResult details(int id)
        {
            var data = bonusRep.GetById(id);
            var model = _mapper.Map<BonusVM>(data);
            return View(model);
        }
        [HttpGet]
        public IActionResult edit(int id)
        {
            var data = bonusRep.GetById(id);
            var model = _mapper.Map<BonusVM>(data);

            return View(model);
        }
        [HttpPost]
        public IActionResult edit(BonusVM model)
        {
            try
            {
                return editBonus(model);
            }
            catch
            {
                return View(model);
            }
        }
        [HttpGet]
        public IActionResult delete(int id)
        {
            var data = bonusRep.GetById(id);
            var model = _mapper.Map<BonusVM>(data);

            return View(model);
        }
        [HttpPost]
        public IActionResult delete(BonusVM model)
        {
            try
            {
                var data = _mapper.Map<bonuss>(model);
                bonusRep.Delete(data.id);
                return RedirectToAction("Index");
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "Not Deleted");
                return View(model);
            }
        }
        private IActionResult editBonus(BonusVM model)
        {
            if (ModelState.IsValid)
            {
                var data = _mapper.Map<bonuss>(model);
                bonusRep.Update(data);
                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }
        [HttpPost]
        public JsonResult getBonusById(int  id)
        {
            var data = bonusRep.GetById(id);
            var model = _mapper.Map<BonusVM>(data);
            return Json(model);
        }
        [HttpPost]
        public JsonResult getAllbonuses()
        {
            var data = bonusRep.GetAll().Select(o => new { o.id, o.bonusName }).ToList();

            return Json(data);
        }
    }
}

companyHR/Controllers/JobController.cs
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
using company.BL.Model;
using company.DAL.Repository.Models;
using RepositoryUsingEFinMVC.GenericRepository;
using Microsoft.AspNetCore.Authorization;

namespace companyHR.Controllers
{
    [Authorize]

    public class JobController : Controller
    {


        private readonly IMapper _mapper;
        private IGenericRepository<job> jobRep;
        public JobController(IGenericRepository<job> _jobRep, IMapper mapper)
        {

            this.jobRep = _jobRep;
            this._mapper = mapper;
        }
        public IActionResult Index()
        {
            var data = jobRep.GetAll();
            var model = _mapper.Map<IEnumerable<jobVM>>(data);
            return View(model);
        }
        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public IActionResult Create(jobVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var data = _mapper.Map<job>(model);
                    jobRep.Insert(data);

                    return RedirectToAction("Index");
                }
                else
                {
                    return View(model);
                }

            }
            catch
            {
                return View(model);

            }

        }
        [HttpGet]
        public IActionResult details(int id)
        {
            var data = jobRep.GetById(id);
            var model = _mapper.Map<jobVM>(data);
            return View(model);
        }
        [HttpGet]
        public IActionResult edit(int id)
        {
            var data = jobRep.GetById(id);
            var model = _mapper.Map<jobVM>(data);

            return View(model);
        }

        [HttpPost]
        public IActionResult edit(jobVM model)
        {
            try
            {
                return editjob(model);
            }
            catch
            {
                return View(model);
            }

        }



        [HttpGet]
        public IActionResult delete(int id)
        {
            var data = jobRep.GetById(id);
            var model = _mapper.Map<jobVM>(data);

            return View(model);
        }
        [HttpPost]
        public IActionResult delete(jobVM model)
        {

            try
            {
                var data = _mapper.Map<job>(model);
                jobRep.Delete(data.id);

                return RedirectToAction("Index");


            }
            catch
            {
                return View(model);

            }
        }


        private IActionResult editjob(jobVM model)
        {
            if (ModelState.IsValid)
            {

                var data = _mapper.Map<job>(model);
                jobRep.Update(data);

                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }
        [HttpGet]
        public JsonResult getAllJobs()
        {
            var data = jobRep.GetAll().Select(o => new { o.id, o.jobName }).ToList();

            return Json(data);
        }


    }
}

companyHR/Controllers/RolesController.cs
using company.BL.Model;
using company.DAL.Extend;
using company.DAL.Repository.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualBasic;
using AutoMapper;
using System.Data;

namespace companyHR.Controllers
{
    [Authorize]

    public class RolesController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly RoleManager<ApplictionRoles> roleManager;
        private readonly IMapper mapper;

        public RolesController(UserManager<ApplicationUser> userManager,RoleManager<ApplictionRoles> roleManager, IMapper mapper) 
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
            this.mapper = mapper;
        }    
        public IActionResult  Index()
        {
            IEnumerable<ApplictionRoles> result =  roleManager.Roles;
            var data = mapper.Map<IEnumerable<ApplictionRolesVm>>(result);

            return View(data);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public  async Task<IActionResult> Create(ApplictionRolesVm identityRole)
        {
            try
            {


                return await CreateRole(identityRole);
            }
            catch
            {
                return View(identityRole);

            }

        }

        private async Task<IActionResult> CreateRole(ApplictionRolesVm identityRole)
        {


            if (ModelState.IsValid)
            {
                var role = new ApplictionRoles()
                {
                    Name = identityRole.Name,
                    NormalizedName = identityRole.Name.ToLower(),
                };






                var resule = await roleManager.CreateAsync(role);
                if (resule.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var item in resule.Errors)
                    {
                        ModelState.AddModelError("", item.Description);

                    }
                    return View(identityRole);

                }
            }
            ModelState.AddModelError("", "Role Name is requird");
            return View(identityRole);
        }
        #region EditRole
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {

            ApplictionRoles role = await roleManager.FindByIdAsync(id);
            var data = mapper.Map<ApplictionRolesVm>(role);

            return View(data);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(ApplictionRolesVm identityRole)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var data = mapper.Map<ApplictionRoles> (identityRole);

                    return await EditRole(data);

                }
                else
                {
                    return View(identityRole);

                }

            }
            catch (Exception ex)
            {
                return View(identityRole);
            }
        }

        private async Task<IActionResult> EditRole(IdentityRole identityRole)
        {
            var role = await roleManager.FindByIdAsync(identityRole.Id);
            role.Name = identityRole.Name;
            role.NormalizedName = identityRole.Name.ToUpper();
            var result = await roleManager.UpdateAsync(role);
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }
                return View(identityRole);
            }
        }
        #endregion

        #region DeleteRole
        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {



            ApplictionRoles role = await roleManager.FindByIdAsync(id);
            var data = mapper.Map<ApplictionRolesVm>(role);

            return View(data);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(ApplictionRolesVm identityRole)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var data = mapper.Map<ApplictionRoles>(identityRole);

                    return await DeleteRole(data);

                }
                else
                {
                    return View(identityRole);

                }

            }
            catch (Exception ex)
            {
                return View(identityRole);
            }
        }
        private async Task<IActionResult> DeleteRole(ApplictionRoles identityRole)
        {
            ApplictionRoles role = await roleManager.FindByIdAsync(identityRole.Id);
            var result = await roleManager.DeleteAsync(role);
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            else
            {
                var data = mapper.Map<ApplictionRolesVm>(identityRole);

                return View(data);
            }
        }
        #endregion

        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            ApplictionRoles role = await roleManager.FindByIdAsync(id);
            var data = mapper.Map<ApplictionRolesVm>(role);

            return View(data);
        }


    }
}
 

companyHR/Controllers/UsersController.cs
using company.BL.Model;
using company.DAL.Extend;
using Demo.BL.Helper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
//using System.Web.Mvc;
using AutoMapper;

namespace companyHR.Controllers
{
    [Authorize]

    public class UsersController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IMapper mapper;

        public UsersController(UserManager<ApplicationUser> userManager, IMapper _mapper) 
        {
            this.userManager = userManager;
            this.mapper = _mapper;
        }    
        public IActionResult Index()
        {
            var users = userManager.Users;
            var model = mapper.Map<IEnumerable<ApplicationUserVm>>(users);
           

            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            var user = await userManager.FindByIdAsync(id);
            var model = mapper.Map<ApplicationUserVm>(user);

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(ApplicationUserVm UserVm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    return await EditUser(UserVm);
                }
                else
                {
                    ModelState.AddModelError("", "Error ");
                    var user = await userManager.FindByIdAsync(UserVm.Id);
                    var model = mapper.Map<ApplicationUserVm>(user);

                    return View(model);
                }

            }
            catch(Exception ex)
            {
                var user = await userManager.FindByIdAsync(UserVm.Id);
                var model = mapper.Map<ApplicationUserVm>(user);

                return View(model);

            }
        }
        private async Task<IActionResult> EditUser(ApplicationUserVm UserVm)
        {
            ApplicationUser model = await userManager.FindByIdAsync(UserVm.Id);
            string FolderPath = "/wwwroot/Files/UsersImages";

            if (UserVm.Photo != null)
            {
                
                string fileName=FileUploader.UploadFile(FolderPath, UserVm.Photo);
                model.PhotoName = fileName;

            }
            else
            {
                if( UserVm.PhotoName == null|| UserVm.PhotoName == "")
                {
                     FileUploader.RemoveFile(FolderPath, model.PhotoName);
                     model.PhotoName = null;
                }
               
            }
            model.UserName = UserVm.UserName;
            model.Email=UserVm.Email;

           

            var result = await userManager.UpdateAsync(model);
            if (result.Succeeded)
            {

                return RedirectToAction("Index");

            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }
                return View(UserVm);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            ApplicationUser user = await userManager.FindByIdAsync(id);
            var model = mapper.Map<ApplicationUserVm>(user);

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(ApplicationUserVm applicationUser)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    ApplicationUser user = await userManager.FindByIdAsync(applicationUser.Id);
                    string FolderPath = "/wwwroot/Files/UsersImages";
                    string PhotoName = user.PhotoName;
                    var result= await userManager.DeleteAsync(user);
                    if (result.Succeeded)
                    {
                        if (PhotoName != null || PhotoName != "")
                        {
                        FileUploader.RemoveFile(FolderPath, PhotoName);
                        }
                        return RedirectToAction("Index");
                    }
                    else
                    {               
                        return View(applicationUser);
                    }
                }
                else
                {
                return View(applicationUser);

                }

            }
            catch (Exception ex)
            {
                return View(applicationUser);
            }
        }


        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            ApplicationUser user = await userManager.FindByIdAsync(id);
            var model = mapper.Map<ApplicationUserVm>(user);
            return View(model);
        }
    }
}

companyHR/Views/PartialView/PartialLayout/footer.cshtml
<div class="legal">
    <div class="copyright">
        &copy;@DateTime.Now.Year <a href="javascript:void(0);">AdminBSB - AliSHalaby</a>.
    </div>
    <div class="version">
        <b>Version: </b> 1
    </div>
</div>

companyHR/Views/PartialView/PartialLayout/menu.cshtml
@using company.DAL.Extend;
@inject UserManager<ApplicationUser> applicationUser;
@inject RoleManager<ApplictionRoles> roleManager;
@inject company.BL.Interface.IMenuRep menu;
@{
    ApplicationUser application = await applicationUser.FindByNameAsync(User.Identity.Name);
    var PhotoName = application.PhotoName;
    IList<string> roles = await applicationUser.GetRolesAsync(application);
    List<string> rolesid = roleManager.Roles.Where(o => roles.Contains(o.Name)).Select(o => o.Id).ToList();
    var menuData = menu.GetMenu(rolesid).ToList();
}

<aside id="sidebar" class="sidebar">


@*     @foreach(var item in menuData)
    {
        if(item.Page.ParentiD==null)
        {
            <h1>@item.Page.PageName</h1>
            foreach (var subMenu in menuData)
            {
                if(subMenu.Page.ParentiD==item.Page.Id)
                {
                    <h4 style="font-size:10px;">@subMenu.Page.PageName </h4>
                }
            }
        }
    } *@


    <ul class="sidebar-nav" id="sidebar-nav">

   @foreach(var item in menuData)
    {
            if (item.parentId == null && item.pageControl == null)
        {
             <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#menu-@item.pageid" data-bs-toggle="collapse" href="#">
                        <i class="bi bi-menu-button-wide"></i><span>@item.pageNAme</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
                    <ul id="menu-@item.pageid" class="nav-content collapse " data-bs-parent="#sidebar-nav">


          @foreach (var subMenu in menuData)
            {
                if(subMenu.parentId==item.pageid)
                {
                                <li>
                                    <a asp-controller="@subMenu.pageControl" asp-action="@subMenu.pageAction">
                                        <i class="bi bi-circle"></i><span>@subMenu.pageNAme</span>
                                    </a>
                                </li>
                }
            }


                    </ul>
                </li>

            }
            else if(item.parentId==null&& item.pageControl != null)
            {
                <li class="nav-item">
                    <a class="nav-link " asp-controller="@item.pageControl" asp-action="@item.pageAction">
                        <i class="bi bi-grid"></i>
                        <span>DashBoard</span>
                    </a>
                </li>

                <!-- End Dashboard Nav -->
            }
        }


@*         <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#EmployeesBonus" data-bs-toggle="collapse" href="#">
                <i class="bi bi-menu-button-wide"></i><span>Employees Bonus/Deduction</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="EmployeesBonus" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a asp-controller="EmployeeBonus" asp-action="index">
                        <i class="bi bi-circle"></i><span>Bonus/Deduction</span>
                    </a>
                </li>

            </ul>
        </li>

        <li class="nav-item">
            <a class="nav-link " asp-controller="home" asp-action="index">
                <i class="bi bi-grid"></i>
                <span>DashBoard</span>
            </a>
        </li><!-- End Dashboard Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#MainData" data-bs-toggle="collapse" href="#">
                <i class="bi bi-menu-button-wide"></i><span>Main Data</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="MainData" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a asp-controller="Employees" asp-action="index">
                        <i class="bi bi-circle"></i><span>Employees</span>
                    </a>
                </li>
                <li>
                    <a asp-controller="department" asp-action="index">
                        <i class="bi bi-circle"></i><span>Departments</span>
                    </a>
                </li>

                <li>
                    <a asp-controller="Job" asp-action="index">
                        <i class="bi bi-circle"></i><span>Jobs</span>
                    </a>
                </li>
                <li>
                    <a asp-controller="Bonuss" asp-action="index">
                        <i class="bi bi-circle"></i><span>Bonus</span>
                    </a>
                </li>
                <li>
                    <a asp-controller="Vacation" asp-action="index">
                        <i class="bi bi-circle"></i><span>Vacations</span>
                    </a>
                </li>
            </ul>
        </li><!-- End Components Nav -->


        <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#EmployeesBonus" data-bs-toggle="collapse" href="#">
                <i class="bi bi-menu-button-wide"></i><span>Employees Bonus/Deduction</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="EmployeesBonus" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a asp-controller="EmployeeBonus" asp-action="index">
                        <i class="bi bi-circle"></i><span>Bonus/Deduction</span>
                    </a>
                </li>

            </ul>
        </li><!-- End Components Nav -->


        <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#EmployeesVacations" data-bs-toggle="collapse" href="#">
                <i class="bi bi-menu-button-wide"></i><span>Employees Vacations</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="EmployeesVacations" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a asp-controller="EmployeesVacation" asp-action="index">
                        <i class="bi bi-circle"></i><span>Vacation</span>
                    </a>
                </li>

            </ul>
        </li><!-- End Components Nav -->


        <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#Security" data-bs-toggle="collapse" href="#">
                <i class="bi bi-menu-button-wide"></i><span>Security</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="Security" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a asp-controller="Users" asp-action="index">
                        <i class="bi bi-circle"></i><span>Users</span>
                    </a>
                </li>
                <li>
                    <a asp-controller="Roles" asp-action="index">
                        <i class="bi bi-circle"></i><span>Roles</span>
                    </a>
                </li>
                <li>
                    <a asp-controller="AddRemoveRoles" asp-action="index">
                        <i class="bi bi-circle"></i><span>Users Roles</span>
                    </a>
                </li>

            </ul>
        </li><!-- End Components Nav --> *@




    </ul>

</aside>